"""
Git module for py-claw runtime.

Provides git operations, parsing, and types for the py-claw runtime.

Based on ClaudeCode-main/src/utils/git.ts
"""
from py_claw.git.operations import (
    fetch_git_diff,
    fetch_git_diff_hunks,
    find_git_root,
    find_remote_base,
    get_branch,
    get_changed_files,
    get_default_branch,
    get_file_status,
    get_git_dir,
    get_git_state,
    get_head,
    get_is_clean,
    get_is_git,
    get_is_head_on_remote,
    get_remote_url,
    get_repo_remote_hash,
    get_worktree_count,
    git_exe,
    has_unpushed_commits,
    is_at_git_root,
    is_current_directory_bare_git_repo,
    preserve_git_state_for_issue,
    stash_to_clean_state,
)
from py_claw.git.parsers import (
    is_binary_file_extension,
    parse_diff_line,
    parse_git_diff_hunks,
    parse_git_numstat,
    parse_shortstat,
)
from py_claw.git.types import (
    BINARY_EXTENSIONS,
    GIT_TIMEOUT_MS,
    MAX_DIFF_SIZE_BYTES,
    MAX_FILES,
    MAX_FILES_FOR_DETAILS,
    MAX_LINES_PER_FILE,
    GitDiffOptions,
    GitDiffResult,
    GitDiffStats,
    GitFileStatus,
    GitRepoState,
    NumstatResult,
    ParsedRepository,
    PerFileStats,
    PreservedGitState,
    StructuredPatchHunk,
    ToolUseDiff,
)


__all__ = [
    # Operations
    "fetch_git_diff",
    "fetch_git_diff_hunks",
    "find_git_root",
    "find_remote_base",
    "get_branch",
    "get_changed_files",
    "get_default_branch",
    "get_file_status",
    "get_git_dir",
    "get_git_state",
    "get_head",
    "get_is_clean",
    "get_is_git",
    "get_is_head_on_remote",
    "get_remote_url",
    "get_repo_remote_hash",
    "get_worktree_count",
    "git_exe",
    "has_unpushed_commits",
    "is_at_git_root",
    "is_current_directory_bare_git_repo",
    "preserve_git_state_for_issue",
    "stash_to_clean_state",
    # Parsers
    "is_binary_file_extension",
    "parse_diff_line",
    "parse_git_diff_hunks",
    "parse_git_numstat",
    "parse_shortstat",
    # Types
    "BINARY_EXTENSIONS",
    "GIT_TIMEOUT_MS",
    "GitDiffOptions",
    "GitDiffResult",
    "GitDiffStats",
    "GitFileStatus",
    "GitRepoState",
    "MAX_DIFF_SIZE_BYTES",
    "MAX_FILES",
    "MAX_FILES_FOR_DETAILS",
    "MAX_LINES_PER_FILE",
    "NumstatResult",
    "ParsedRepository",
    "PerFileStats",
    "PreservedGitState",
    "StructuredPatchHunk",
    "ToolUseDiff",
]
