"""
Utility functions for py_claw.

Common utilities for error handling, JSON, path manipulation, and environment.
"""
from __future__ import annotations

from .hooks import (
    HookBlockingError,
    BaseHookInput,
    HookMatchResult,
    get_session_end_hook_timeout_ms,
    get_tool_hook_timeout_ms,
    matches_pattern,
    get_hook_display_text,
    create_base_hook_input,
    parse_hook_query,
    validate_hook_json,
    process_hook_json_output,
    get_matching_hooks,
    dedupe_hooks,
    has_blocking_result,
    get_pre_tool_hook_blocking_message,
    get_stop_hook_message,
    should_skip_hook_due_to_trust,
)
from .errors import (
    ErrorContext,
    error_message,
    get_error_context,
    CliError,
    ConfigError,
    AuthError,
    ToolError,
    PermissionError,
    NetworkError,
    ValidationError,
    is_user_facing_error,
    format_error_for_display,
)
from .json import (
    json_parse,
    json_stringify,
    safe_json_parse,
    is_json_string,
    normalize_json_key,
)
from .path import (
    normalize_path,
    is_absolute_path,
    join_paths,
    get_home_dir,
    get_config_home,
    get_cache_dir,
    ensure_dir_exists,
    is_subpath,
    windows_to_posix_path,
    posix_to_windows_path,
    get_relative_path,
    path_to_uri,
    uri_to_path,
)
from .env import (
    EnvInfo,
    get_env_info,
    is_ci,
    is_test,
    is_production,
    is_development,
    get_env_bool,
    get_env_int,
    get_env_str,
    is_env_truthy,
    get_required_env,
    get_claude_config_dir,
    get_claude_data_dir,
)
from .auth import (
    ApiKeySource,
    ApiKeyResult,
    OAuthTokens,
    is_bare_mode,
    is_anthropic_auth_enabled,
    has_anthropic_api_key_auth,
    get_anthropic_api_key,
    get_anthropic_api_key_with_source,
    get_auth_token_source,
    is_claude_ai_subscriber,
    get_subscription_type,
    is_max_subscriber,
    is_pro_subscriber,
    is_team_subscriber,
    is_enterprise_subscriber,
    get_subscription_name,
    has_opus_access,
    get_claude_ai_oauth_tokens,
    is_oauth_token_expired,
    clear_oauth_token_cache,
    get_api_key_from_api_key_helper,
    clear_api_key_helper_cache,
    is_env_truthy as auth_is_env_truthy,
    is_running_on_homespace,
)
from .api import (
    ToolSchemaCache,
    get_tool_schema_cache,
    tool_to_api_schema,
    SystemPromptBlock,
    split_sys_prompt_prefix,
    append_system_context,
    prepend_user_context,
    normalize_tool_input,
    normalize_tool_input_for_api,
    log_api_prefix,
    ContextMetrics,
    calculate_context_metrics,
)
from .log import (
    ErrorLogSink,
    log_error,
    get_in_memory_errors,
    log_mcp_error,
    log_mcp_debug,
    attach_error_log_sink,
    load_error_logs_from_dir,
    date_to_filename,
    _reset_error_log_for_testing,
)
from .debug import (
    is_debug_mode,
    enable_debug_logging,
    is_debug_to_stderr,
    get_debug_file_path,
    set_has_formatted_output,
    get_has_formatted_output,
    get_debug_log_path,
    log_for_debugging,
    flush_debug_logs,
    log_ant_error,
    DebugLogWriter,
)
from .stats import (
    DailyActivity,
    DailyModelTokens,
    StreakInfo,
    SessionStats,
    ClaudeCodeStats,
    to_date_string,
    get_today_date_string,
    get_yesterday_date_string,
    is_date_before,
    calculate_streaks,
    process_session_files,
    aggregate_claude_code_stats,
)
from .session_state import (
    SessionState,
    RequiresActionDetails,
    SessionExternalMetadata,
    get_session_state,
    notify_session_state_changed,
    notify_session_metadata_changed,
    notify_permission_mode_changed,
    set_session_state_changed_listener,
    set_session_metadata_changed_listener,
    set_permission_mode_changed_listener,
)
from .cron import (
    CronFields,
    parse_cron_expression,
    compute_next_cron_run,
    cron_to_human,
)
from .cleanup import (
    CleanupResult,
    cleanup_old_files_in_directory,
    cleanup_old_message_files,
    cleanup_old_session_files,
    cleanup_old_plan_files,
    cleanup_old_debug_logs,
    cleanup_old_session_env_dirs,
    cleanup_old_file_history_backups,
    cleanup_old_message_files_in_background,
)
from .extra_usage import (
    is_billed_as_extra_usage,
)
from .fast_mode import (
    FastModeState,
    get_fast_mode_state,
    set_fast_mode_state,
    handle_fast_mode_rejected_by_api,
    handle_fast_mode_overage_rejection,
    trigger_fast_mode_cooldown,
    clear_fast_mode_cooldown,
    is_in_fast_mode_cooldown,
    get_fast_mode_cooldown_remaining_seconds,
    set_fast_mode_cooldown_callback,
    set_fast_mode_overage_callback,
)
from .background_housekeeping import (
    start_background_housekeeping,
)
from .exec_file_no_throw import (
    ExecResult,
    exec_file_no_throw,
    exec_file_no_throw_async,
)
from .embedded_tools import (
    has_embedded_search_tools,
    embedded_search_tools_binary_path as get_embedded_search_tools_binary_path,
)
from .early_input import (
    start_capturing_early_input,
    consume_early_input,
    seed_early_input,
    has_early_input,
    stop_capturing_early_input as clear_early_input,
)
from .auth_portable import (
    maybe_remove_api_key_from_mac_os_keychain,
    normalize_api_key_for_config,
)
from .auth_file_descriptor import (
    is_file_descriptor_auth_supported,
    get_auth_file_descriptor,
)
from .code_indexing import (
    CodeIndexingTool,
    detect_code_indexing_from_command,
    detect_code_indexing_from_mcp_tool,
    detect_code_indexing_from_mcp_server_name,
)
from .desktop_deep_link import (
    build_desktop_deep_link,
    is_desktop_installed,
    get_desktop_version,
    get_desktop_install_status,
    open_current_session_in_desktop,
    _is_dev_mode,
)
from .asciicast import (
    get_record_file_path,
    _reset_recording_state_for_testing,
    get_session_recording_paths,
    flush_asciicast_recorder,
    install_asciicast_recorder,
)
from .conversation_recovery import (
    TurnInterruptionState,
    DeserializeResult,
    migrate_legacy_attachment_types,
    deserialize_messages,
    deserialize_messages_with_interrupt_detection,
)
from .commit_attribution import (
    INTERNAL_MODEL_REPOS,
    get_attribution_repo_root,
    get_repo_class_cached,
    is_internal_model_repo_cached,
    is_internal_model_repo,
    sanitize_model_name,
    sanitize_surface_key,
    reset_repo_class_cache,
)
from .cursor import (
    KILL_RING_MAX_SIZE,
    push_to_kill_ring,
    get_last_kill,
    get_kill_ring_item,
    get_kill_ring_size,
    clear_kill_ring,
    reset_kill_accumulation,
    record_yank,
    can_yank_pop,
    yank_pop,
    update_yank_length,
    reset_yank_state,
    get_yank_position,
    _reset_for_testing,
)
from .uuid import (
    validate_uuid,
    create_agent_id,
)
from .tempfile import (
    generate_temp_file_path,
)
from .xml import (
    escape_xml,
    escape_xml_attr,
)
from .yaml import (
    parse_yaml,
)

__all__ = [
    # Hook utilities
    "HookBlockingError",
    "BaseHookInput",
    "HookMatchResult",
    "get_session_end_hook_timeout_ms",
    "get_tool_hook_timeout_ms",
    "matches_pattern",
    "get_hook_display_text",
    "create_base_hook_input",
    "parse_hook_query",
    "validate_hook_json",
    "process_hook_json_output",
    "get_matching_hooks",
    "dedupe_hooks",
    "has_blocking_result",
    "get_pre_tool_hook_blocking_message",
    "get_stop_hook_message",
    "should_skip_hook_due_to_trust",
    # Error utilities
    "ErrorContext",
    "error_message",
    "get_error_context",
    "CliError",
    "ConfigError",
    "AuthError",
    "ToolError",
    "PermissionError",
    "NetworkError",
    "ValidationError",
    "is_user_facing_error",
    "format_error_for_display",
    # JSON utilities
    "json_parse",
    "json_stringify",
    "safe_json_parse",
    "is_json_string",
    "normalize_json_key",
    # Path utilities
    "normalize_path",
    "is_absolute_path",
    "join_paths",
    "get_home_dir",
    "get_config_home",
    "get_cache_dir",
    "ensure_dir_exists",
    "is_subpath",
    "windows_to_posix_path",
    "posix_to_windows_path",
    "get_relative_path",
    "path_to_uri",
    "uri_to_path",
    # Environment utilities
    "EnvInfo",
    "get_env_info",
    "is_ci",
    "is_test",
    "is_production",
    "is_development",
    "get_env_bool",
    "get_env_int",
    "get_env_str",
    "is_env_truthy",
    "get_required_env",
    "get_claude_config_dir",
    "get_claude_data_dir",
    # Auth utilities
    "ApiKeySource",
    "ApiKeyResult",
    "OAuthTokens",
    "is_bare_mode",
    "is_anthropic_auth_enabled",
    "has_anthropic_api_key_auth",
    "get_anthropic_api_key",
    "get_anthropic_api_key_with_source",
    "get_auth_token_source",
    "is_claude_ai_subscriber",
    "get_subscription_type",
    "is_max_subscriber",
    "is_pro_subscriber",
    "is_team_subscriber",
    "is_enterprise_subscriber",
    "get_subscription_name",
    "has_opus_access",
    "get_claude_ai_oauth_tokens",
    "is_oauth_token_expired",
    "clear_oauth_token_cache",
    "get_api_key_from_api_key_helper",
    "clear_api_key_helper_cache",
    "auth_is_env_truthy",
    "is_running_on_homespace",
    # API utilities
    "ToolSchemaCache",
    "get_tool_schema_cache",
    "tool_to_api_schema",
    "SystemPromptBlock",
    "split_sys_prompt_prefix",
    "append_system_context",
    "prepend_user_context",
    "normalize_tool_input",
    "normalize_tool_input_for_api",
    "log_api_prefix",
    "ContextMetrics",
    "calculate_context_metrics",
    # Log utilities
    "ErrorLogSink",
    "log_error",
    "get_in_memory_errors",
    "log_mcp_error",
    "log_mcp_debug",
    "attach_error_log_sink",
    "load_error_logs_from_dir",
    "date_to_filename",
    "_reset_error_log_for_testing",
    # Debug utilities
    "is_debug_mode",
    "enable_debug_logging",
    "is_debug_to_stderr",
    "get_debug_file_path",
    "set_has_formatted_output",
    "get_has_formatted_output",
    "get_debug_log_path",
    "log_for_debugging",
    "flush_debug_logs",
    "log_ant_error",
    "DebugLogWriter",
    # Stats utilities
    "DailyActivity",
    "DailyModelTokens",
    "StreakInfo",
    "SessionStats",
    "ClaudeCodeStats",
    "to_date_string",
    "get_today_date_string",
    "get_yesterday_date_string",
    "is_date_before",
    "calculate_streaks",
    "process_session_files",
    "aggregate_claude_code_stats",
    # Session state utilities
    "SessionState",
    "RequiresActionDetails",
    "SessionExternalMetadata",
    "get_session_state",
    "notify_session_state_changed",
    "notify_session_metadata_changed",
    "notify_permission_mode_changed",
    "set_session_state_changed_listener",
    "set_session_metadata_changed_listener",
    "set_permission_mode_changed_listener",
    # Cron utilities
    "CronFields",
    "parse_cron_expression",
    "compute_next_cron_run",
    "cron_to_human",
    # Cleanup utilities
    "CleanupResult",
    "cleanup_old_files_in_directory",
    "cleanup_old_message_files",
    "cleanup_old_session_files",
    "cleanup_old_plan_files",
    "cleanup_old_debug_logs",
    "cleanup_old_session_env_dirs",
    "cleanup_old_file_history_backups",
    "cleanup_old_message_files_in_background",
    # Extra usage
    "is_billed_as_extra_usage",
    # Fast mode
    "FastModeState",
    "get_fast_mode_state",
    "set_fast_mode_state",
    "handle_fast_mode_rejected_by_api",
    "handle_fast_mode_overage_rejection",
    "trigger_fast_mode_cooldown",
    "clear_fast_mode_cooldown",
    "is_in_fast_mode_cooldown",
    "get_fast_mode_cooldown_remaining_seconds",
    "set_fast_mode_cooldown_callback",
    "set_fast_mode_overage_callback",
    # Background housekeeping
    "start_background_housekeeping",
    # Exec file no throw
    "ExecResult",
    "exec_file_no_throw",
    "exec_file_no_throw_async",
    # Embedded tools
    "has_embedded_search_tools",
    "get_embedded_search_tools_binary_path",
    # Early input
    "start_capturing_early_input",
    "consume_early_input",
    "seed_early_input",
    "has_early_input",
    "clear_early_input",
    # Auth portable
    "maybe_remove_api_key_from_mac_os_keychain",
    "normalize_api_key_for_config",
    # Auth file descriptor
    "is_file_descriptor_auth_supported",
    "get_auth_file_descriptor",
    # Code indexing
    "CodeIndexingTool",
    "detect_code_indexing_from_command",
    "detect_code_indexing_from_mcp_tool",
    "detect_code_indexing_from_mcp_server_name",
    # Desktop deep link
    "build_desktop_deep_link",
    "is_desktop_installed",
    "get_desktop_version",
    "get_desktop_install_status",
    "open_current_session_in_desktop",
    "_is_dev_mode",
    # Asciicast
    "get_record_file_path",
    "_reset_recording_state_for_testing",
    "get_session_recording_paths",
    "flush_asciicast_recorder",
    "install_asciicast_recorder",
    # Conversation recovery
    "TurnInterruptionState",
    "DeserializeResult",
    "migrate_legacy_attachment_types",
    "deserialize_messages",
    "deserialize_messages_with_interrupt_detection",
    # Commit attribution
    "INTERNAL_MODEL_REPOS",
    "get_attribution_repo_root",
    "get_repo_class_cached",
    "is_internal_model_repo_cached",
    "is_internal_model_repo",
    "sanitize_model_name",
    "sanitize_surface_key",
    "reset_repo_class_cache",
    # Cursor / Kill ring
    "KILL_RING_MAX_SIZE",
    "push_to_kill_ring",
    "get_last_kill",
    "get_kill_ring_item",
    "get_kill_ring_size",
    "clear_kill_ring",
    "reset_kill_accumulation",
    "record_yank",
    "can_yank_pop",
    "yank_pop",
    "update_yank_length",
    "reset_yank_state",
    "get_yank_position",
    "_reset_for_testing",
    # UUID utilities
    "validate_uuid",
    "create_agent_id",
    # Tempfile utilities
    "generate_temp_file_path",
    # XML utilities
    "escape_xml",
    "escape_xml_attr",
    # YAML utilities
    "parse_yaml",
]
